### PR TITLE
Option to disable status requests

### PR DESCRIPTION
**Pull request by Paul-Reed**
This PR introduces a checkbox in the dimmer node config which enables users to disable/enable status reports being produced after each command.
The default state of the checkbox is 'enabled' to maintain compatibility with existing flows.
If unchecked, a status report can still be requested by injecting a blank msg.payload (unchanged).

The reason for introducing this is to resolve issue https://github.com/windkh/node-red-contrib-shelly/issues/21

### CODE REVIEW

**Review by windkh — APPROVED** [review]

**Comment by windkh** [comment]
I got the idea of not getting the status, however why did you name the property dimmerStat?

**Comment by Paul-Reed** [comment]
I appreciate that you've been busy, but as it's 27 days since I submitted this PR, I assumed that you did not want the update, so I've now written and used my own Shelly node instead.

I used the name 'dimmerStat' because it's a shortened name for 'dimmer status', but if you would prefer some other name, please feel free to change it to whatever you wish (I've enabled allow edits by maintainers).

**Comment by windkh** [comment]
... and a final question: why did you want to skip getting the status?

**Comment by Paul-Reed** [comment]
I gave you an 'issue' link in the post above which describes the reason...

> This PR introduces a checkbox in the dimmer node config which enables users to disable/enable status reports being produced after each command.
> The default state of the checkbox is 'enabled' to maintain compatibility with existing flows.
> If unchecked, a status report can still be requested by injecting a blank msg.payload (unchanged).
> 
> The reason for introducing this is to resolve issue #21

**Comment by windkh** [comment]
A ok ... got it. I will merge all the changes together with other pull requests and then create a new version.
Thanks alot

**Pull request merged**
