### PR TITLE
feat: add roller shutter

### PR DESCRIPTION
**Pull request by gerdemann**

### CODE REVIEW

**Comment by gerdemann** [comment]
@windkh Hey, is it possible to get this merged?

**Comment by windkh** [comment]
Yes ofcourse. Thanks alot! I will do this asap.

**Comment by windkh** [comment]
I am still waiting for my ordered hardware,... sorry for delay

**Comment by windkh** [comment]
I blindly merged without testing it.... thanks!!!

**Comment by windkh** [comment]
@gerdemann can you provide an example under the examples folder?

**Pull request merged**
